name: change ami-id in pre-pod
on:
  push:
    branches: main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        KEY: ${{ secrets.KEY }}

    steps:
      - name: install aws-cli
        run: sudo apt install awscli -y

      - name: configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: create an instance
        run: | 
          aws ec2 run-instances --image-id ami-0f93563a114d0bee1 --instance-type t2.micro --key-name key001 --query 'Instances[0].[InstanceId]' --output text > instance_id.txt

          cat instance_id.txt

      - name: pull artifact from s3 
        run: aws s3 cp s3://s3newbucket7890/pro-html.zip pro-html.zip

      - name: store public ip of instance
        run: | 
          aws ec2 describe-instances --instance-ids $(cat instance_id.txt) --query 'Reservations[0].Instances[0].[PublicIpAddress]' --output text > instance_ip.txt
          
          cat instance_ip.txt

     
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 35.174.171.37
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: 'pro-html.zip'
          target: '/home/ubuntu'    
          

          

              



 